[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_ENABLE_REAL_AI = "false"
  NEXT_PUBLIC_ENABLE_MOCK_MODE = "true"
  NEXT_PUBLIC_ENABLE_DEBUG_LOGS = "false"
